name: Nightly Google Sheets → Neon ETL

on:
  schedule:
    - cron: "15 1 * * *"  # runs daily at 01:15 UTC
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary gspread oauth2client pandas

      - name: Write Google credentials file from secret
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > powerbi-etl-creds.json
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Run ETL
        env:
          DB_URI: ${{ secrets.DB_URI }}
          ETL_CONFIG_FILE: config.json
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/powerbi-etl-creds.json
        run: |
          python ETLGS_Postgres_gsheet_Render_FIXED.py
