
name: Nightly Google Sheets → BigQuery

on:
  schedule:
    - cron: "15 1 * * *"  # runs daily at 01:15 UTC
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-bigquery pandas gspread oauth2client

      - name: Write Google credentials file from secret
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > powerbi-etl-creds.json
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Run ETL
        env:
          ETL_CONFIG_FILE: config.json
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/powerbi-etl-creds.json
          GCP_PROJECT: powerbi-etl
          BQ_DATASET: ETL_Dataset
        run: |
          python ETLGS_Postgres_gsheet_Final.py
          
